import axios from 'axios';

const BASE_URL = 'https://api.spotify.com/v1';

export function getCurrentUserProfile(token) {
  return axios.get(`${BASE_URL}/me`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}

export function getRecentlyPlayedTracks(token) {
    return axios.get(`${BASE_URL}/me/player/recently-played?limit=10`, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
  }

  export function createPlaylist(token, userId, name) {
    return axios.post(`${BASE_URL}/users/${userId}/playlists`, 
      {
        name: name,
        description: 'Playlist generated by HighDe app',
        public: false
      },
      {
        headers: {
          Authorization: `Bearer ${token}`
        }
      }
    );
  }
  
  export function addTracksToPlaylist(token, playlistId, uris) {
    return axios.post(`${BASE_URL}/playlists/${playlistId}/tracks`, 
      { uris },
      {
        headers: {
          Authorization: `Bearer ${token}`
        }
      }
    );
  }

  export function getTopTracks(token) {
  return axios.get(`${BASE_URL}/me/top/tracks?limit=30`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}