import axios from 'axios';

const BASE_URL = 'https://api.spotify.com/v1';

export function getCurrentUserProfile(token) {
  return axios.get(`${BASE_URL}/me`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}

export function getRecentlyPlayedTracks(token) {
  return axios.post(`${BASE_URL}/me/player/recently-played?limit=10`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}

export function createPlaylist(token, userId, name) {
  return axios.post(`${BASE_URL}/users/${userId}/playlists`, 
    {
      name: name,
      description: 'Playlist generated by HighDe app',
      public: false
    },
    {
      headers: {
        Authorization: `Bearer ${token}`
      }
    }
  );
}

export function addTracksToPlaylist(token, playlistId, trackUris) {
  return axios.post(`${BASE_URL}/playlists/${playlistId}/tracks`, {
    uris: trackUris
  }, {
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    }
  })
  .catch((error) => {
    console.error("Error in addTracksToPlaylist:", error.response.data);
    throw error; // Re-throw the error to be caught in the calling function
  });
}



export function getTopTracks(token) {
  return axios.get(`${BASE_URL}/me/top/tracks?limit=30`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}

export const getTrackFeatures = async (token, trackId) => {
    return axios.get(`${BASE_URL}/audio-features/${trackId}`, {
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
  }

export function getRecommendations(token, seedTracks) {
  return axios.get(`${BASE_URL}/recommendations?seed_tracks=${seedTracks.join(',')}`, {
    headers: {
      Authorization: `Bearer ${token}`
    }
  });
}
